name: 'CI'

on: push

jobs:
  example:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shard: ["1,5", "2,5", "3,5", "4,5", "5,5"]
    steps:
      - uses: actions/checkout@v3
      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: 5.34.1
          install-modules-with: cpm
          enable-modules-cache: true
      - run: echo PERL5LIB=$PERL5LIB:$PWD/lib:$PWD/local/lib/perl5 >> $GITHUB_ENV
      - run: prove -PShard=${{matrix.shard}} ./example_tests

  test:
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3
      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: 5.34.1
          install-modules-with: cpm
          enable-modules-cache: true
          distribution: ${{ ( matrix.os == 'windows-latest' && 'strawberry') || 'default' }}
      - run: echo PERL5LIB=$PERL5LIB:$PWD/lib:$PWD/local/lib/perl5 >> $GITHUB_ENV
      - name: lint
        run: local/bin/perlcritic ./lib
      - name: format
        run: local/bin/perltidy --assert-tidy ./lib/**/*.pm ./t/**/*.t
      - name: test
        run: prove -lv ./t
